Allow to use modules that are dependencies
This reuse the pm-utils module dependency handling to allow using modules
that are dependencies of other modules (for example, i8042).

diff --git a/suspend-modules b/suspend-modules
--- a/suspend-modules
+++ b/suspend-modules
@@ -1,14 +1,83 @@
 #!/bin/bash
 
+# --------------------
+# "Stolen" from pm-utils.
+
+
+# Look into modularizing this into an os-specific set of support routines.
+_rmmod()
+{
+	if modprobe -r "$1"; then
+		touch "${STORAGEDIR}/module:$1"
+		return 0
+	else
+		log "# could not unload '$1', usage count was $2"
+		return 1
+	fi
+}
+
+# this recursively unloads the given modules and all that depend on it
+# first parameter is the module to be unloaded
+modunload()
+{
+	local MOD D C USED MODS I
+	local UNL="$(echo $1 |tr - _)" RET=1
+
+	while read MOD D C USED D; do
+		[ "$MOD" = "$UNL" ] || continue
+		if [ "$USED" = "-" ]; then
+			# no dependent modules, just try to remove this one.
+			_rmmod "$MOD" $C
+			RET=$?
+		else
+			# modules depend on this one.  try to remove them first.
+			MODS=",${USED%,}"
+			while [ -n "${MODS}" ]; do
+				# try to unload the last one first
+				MOD="${MODS##*,}"
+				modunload $MOD && RET=0
+				# prune the last one from the list
+				MODS="${MODS%,*}"
+			done
+			# if we unloaded at least one module, then let's
+			# try again!
+			[ $RET -eq 0 ] && modunload $MOD
+			RET=$?
+		fi
+		return $RET
+	done < /proc/modules
+	# if we came this far, there was nothing to do,
+	# the module is no longer loaded.
+	return 0
+}
+
+# reload all the modules in no particular order.
+# modprobe should take care of loading prerequisites for us.
+modreload()
+{
+	for x in "${STORAGEDIR}"/module:* ; do
+		[ -O "${x}" ] || continue
+		modprobe "${x##*:}" >/dev/null 2>&1 || \
+			log "Could not reload module ${x##*:}."
+
+	done
+}
+
+# --------------------
+
+STORAGEDIR="/tmp/systemd-suspend-storage"
+
 case $1 in
     pre)
+        mkdir -p "${STORAGEDIR}"
         for mod in $(</etc/suspend-modules.conf); do
-            rmmod $mod
+            modunload $mod
         done
     ;;
     post)
         for mod in $(</etc/suspend-modules.conf); do
-            modprobe $mod
+            modreload $mod
         done
+        rm -f "${STORAGEDIR}/*"
     ;;
 esac
